### ISSUE TITLE
Help with Goals

### ISSUE THREAD

**Issue by marcionicolau** [ankitrohatgi/digitizeR#2]
Hi @ankitrohatgi! How Can I help to develop the goals commented at Readme, specifically about **interaction in real time** with the package? Let me know.

**Comment by jrdnmdhl** [comment]
**Unsolicited advice disclaimer:**
I'm not @ankitrohatgi (obviously), but I'll offer a few unsolicited thoughts which you are certainly free to ignore.

I see two scenarios for web plot digitizer and R communicating in real time:
1. As an input to a proper shiny application where the user can upload an image, digitize it, and the shiny app can capture the resulting data points, pass the JSON to R, and get it converted to data.frame.
2. Data entry during an interactive session (i.e. I have an image of a line chart and want to bring up WPD within R, digitize it, and have a data.frame of the points returned).

The first option should be quite do-able.  The htmlwidgets packages would probably be a useful tool for making this easier to integrate into shiny.

The second option would follow trivially from the first using [shiny-gadgets.](http://shiny.rstudio.com/articles/gadgets.html).

**Comment by ankitrohatgi** [comment]
@jrdnmdhl I am still unsure on how a pure HTML5 GUI is to be used with shiny-gadgets. The website isn't very clear in this area, or maybe there's something obvious I am overlooking. Also, I am a bit reluctant to create dependencies on RStudio and shiny-gadgets due to various reasons (not too reluctant though).

@marcionicolau - For the live communication to work, WPD code needs to implement websockets as well. At the moment, I have very little in place to do that, and it may take me a couple of months to get to it. You are free to look up WPD code as well and see if there's something you want to add. I will gladly accept pull requests. I am expecting the R side of websocket communication to be relatively straightforward.

**Comment by jrdnmdhl** [comment]
@ankitrohatgi

There are several options for defining UIs w/ HTML (I imagine you are interested in first option):
1. [You can write the entire UI in HTML by having an index.html file in the /www subfolder of the app.](http://shiny.rstudio.com/articles/html-ui.html)

2. [You can write the UI mainly in HTML, but have R code fill in specific sections using 'html templates.](http://blog.rstudio.org/2016/01/20/shiny-0-13-0/#more-2434)

3. [You can write the HTML directly using R syntax using shiny's various functions for writing tags.  See below example of some code which defines a bootstrap 3 panel.](http://shiny.rstudio.com/articles/tag-glossary.html).  I suppose this isn't _strictly_ writing it in HTML, but it does map to HTML on a tag-by-tag level.
R: 
```
tags$div(
  class = "panel panel-default",
  tags$div(
    class = "panel-body",
    "A Basic Panel"
  )
)
```

HTML:
```
<div class="panel panel-default">
  <div class="panel-body">A Basic Panel</div>
</div>
```

**Comment by marcionicolau** [comment]
Hi @ankitrohatgi and @jrdnmdhl I´m thinking to use shiny-like approach, but I need to understand the WPD part first. I'll keep in touch.

**Comment by ankitrohatgi** [comment]
@jrdnmdhl Thanks for the pointers!

**Comment by marcionicolau** [comment]
Hi @jrdnmdhl and @ankitrohatgi I think we could close this issue, rigth?
